[package]
name = "btcli"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
authors = ["S.A. (@snoware) <2026>"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
ureq = { version = "3.1.4", features = ["json"] }
serde_json = "1.0.149"
cursive = "0.21.1"
md5 = "0.8.0"
rand = "0.9.2"

[profile.release]
# 优化级别：3(性能优先)、"z"(体积优先)、"s"(平衡)
opt-level = 3

# 链接时优化：false(关闭)、"thin"(推荐)、true(全量)
lto = "thin"

# 代码生成单元：1(单单元)、16(默认)
codegen-units = 16

# Panic处理策略："unwind"(默认)、"abort"(性能优化)
panic = "unwind"

# 符号信息剥离：true(移除调试符号)
strip = true

# CPU特定优化：针对构建机器的CPU特性
target-cpu = "native"
